Add Timezone validation rules to admin prerequisite view #4186
humhub/humhub pull request #4357
Opened 2020-09-10 06:32 UTC by sahartak2025

2020-09-10 08:33 UTC, luke- requested changes
Great, a few notes

2020-09-10 08:33 UTC, luke- commented on CHANGELOG_DEV.md
> +- Fix #4186:Add Timezone validation rules to admin prerequisite view
Please add a whitespace after "Fix #4816:"  and remove the whitespace at the end of the line :-)

2020-09-10 08:33 UTC, luke- commented on protected/humhub/libs/TimezoneHelper.php
> +            $offset_prefix = $dbTimeZoneOffset < 0 ? '-' : '+';
Please use camelCase variable names

2020-09-10 08:33 UTC, luke- commented on protected/humhub/modules/admin/models/forms/BasicSettingsForm.php
> +            'timeZone' => Yii::t('AdminModule.settings', 'Database Timezone: UTC{timeZone}', ['timeZone' => TimezoneHelper::getMysqlTimeZone()]),
Wording: "Reported database time zone: "

2020-09-10 08:33 UTC, luke- commented on protected/humhub/libs/TimezoneHelper.php
> +     * compare db and MySql Timezones
Compares configured time zone with reported database connection time zone

2020-09-10 09:53 UTC, luke- commented
Can you also check how the installer behaves?  Maybe we should remove the time zone check there. Since there is no database configured yet.

2020-09-16 14:08 UTC, artak-sky commented
I fixed your mentioned problems in code and also hide the Timezone setting in the setup page

2020-09-18 09:46 UTC, luke- commented
@artak-sky  Thanks, I've changed it a bit to a lighter approach, i.e. showing the time instead of the timezone.

See modified PR here: https://github.com/humhub/humhub/pull/4392

2020-09-18 09:46 UTC, closed without merging