Update footerNavigation.php
humhub/humhub pull request #4689
Opened 2020-12-04 14:31 UTC by funkycram

Avoid displaying a mid dot at the end of the line

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [X] Other, please describe: Better presentation

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [X] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2020-12-04 14:44 UTC, luke- approved these changes

2020-12-14 13:16 UTC, luke- requested changes
@funkycram Does this really work with PoweredBy Widget enabled? With your PR there is no separation to the "Powered by HumHub" text?

2020-12-14 13:22 UTC, buddh4 commented
Maybe just add the PoweredBy to `$itemHtml` if not empty

2020-12-14 13:41 UTC, funkycram commented
Sorry, the problem was for emails, so in https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/views/footerNavigation_email.php 

But I cannot reproduce... If I have the problem again (dot at the end) I will suggest something !

2020-12-14 13:41 UTC, closed without merging