Enh: Show update tick on AdminMenu
humhub/humhub pull request #5080
Opened 2021-05-23 00:17 UTC by ArchBlood

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Currently, the only way to actually see that there are any updates for modules is if you actually enter the Module tab, this p/r will help admins/those with the permissions to manage modules that there are updates for modules

2021-06-11 19:21 UTC, luke- commented
Thank you for this really good contribution.

I'm a bit concerned that in non-production mode with every admin page request the module update count calculation (incl. REST API request)  is executed. This is because the cache is not fully activated in this mode.

Can you do some tests here? Otherwise I would want to move the feature to Humhub 1.10. There are some module-specific things planned here anyway.

2021-06-11 21:57 UTC, ArchBlood commented
> Thank you for this really good contribution.
> 
> I'm a bit concerned that in non-production mode with every admin page request the module update count calculation (incl. REST API request) is executed. This is because the cache is not fully activated in this mode.
> 
> Can you do some tests here? Otherwise I would want to move the feature to Humhub 1.10. There are some module-specific things planned here anyway.

Sure thing, although I'm not seeing any performance issues on my end and in the network tab, I've seen all greens (Status 200, 302, 304) so I'm sure that no problems with the update counter calculation, if anything it works much faster in dev mode, I'm not currently able to do REST API requests on larger scales when it comes to this so it would be a good idea to draft this p/r and probably add it into the mix for 1.10 🤔

One issue that I did find is that updating the twofa module in dev mode shouldn't be recommended, no cache breaks the QR code visibility with 1.0.3

2021-06-11 22:08 UTC, ArchBlood commented
Overall, my thoughts are that on request it will prioritize what needed information in dev mode over collecting all information as a whole, calculating the number of an update is overall not very stressful on the calls it seems, updating of the module(s) with no cache will of course break some things (i.e external CSS/JS), if a better solution can be made I'm sure that it would have to start in 1.10

2021-06-14 07:54 UTC, luke- commented
@ArchBlood The problem are not the browser network accesses, but could be the requests from the HumHub server itself to our Marketplace Server. I'll mark the PR for 1.10. The beta for 1.9 will hopefully be released today or tomorrow.

2021-09-12 17:20 UTC, ArchBlood commented
After looking at the performance it doesn't seem to show much difference between either prod or dev
![Screenshot_1 (1)](https://user-images.githubusercontent.com/35392110/132996784-f63cb9e2-b97a-4dd9-8b32-03e1be82ae67.png)
![Screenshot_2](https://user-images.githubusercontent.com/35392110/132996786-1e8ddca2-5ce3-4b20-b59e-20e810177f68.png)
![Screenshot_3](https://user-images.githubusercontent.com/35392110/132996790-e3cb7597-6521-4c7b-b7f9-1afe53cf83b4.png)

I will continue to monitor and report back on this if requested

2021-10-06 16:38 UTC, luke- requested changes
I've modified your PR a bit and moved it into a private method.

Here my commit:
https://github.com/humhub/humhub/commit/a5bb9e323661985e1bac11d741e9ceaf26d58b56

Thanks!

2021-10-06 16:38 UTC, luke- commented on protected/humhub/modules/admin/widgets/AdminMenu.php
> +        if (!$module->enabled) {
Hides all further Admin Menu entries when Marketplace is disabled.

2021-10-06 16:38 UTC, luke- commented on protected/humhub/modules/admin/widgets/AdminMenu.php
> +            $updatesBadge = '&nbsp;&nbsp;<span class="label label-default">0</span>';
I think we don't need a badge here when no updates available.

2021-10-06 16:38 UTC, closed without merging