Allow additional toggler for elements with context menu
humhub/humhub pull request #5239
Opened 2021-08-09 10:57 UTC by yurabakhtin

**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**The PR fulfills these requirements:**

- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
This modification is required for https://github.com/humhub/cfiles/issues/100

2021-08-10 12:35 UTC, luke- requested changes
Can you please merge this into `develop` (v1.10).

2021-08-11 05:09 UTC, yurabakhtin commented
@luke- I don't have a permission to merge and push any changes into `develop`.
I just changed the base of this PR to `develop` but now this PR has 10 commits instead of 1 commit https://github.com/humhub/humhub/pull/5239/commits/98ffa314f365bea3c01ad2c57ec57717e488823f. Is it what required or should I create a new PR from `develop` that will have the single commit only?

2021-08-11 08:14 UTC, luke- commented
@yurabakhtin Thanks. I've updated the "develop" change with the latest "master" commits. Now everything looks fine.

2021-08-11 15:36 UTC, luke- approved these changes

2021-08-11 15:36 UTC, merged