Statistic input loading problem #5534
humhub/humhub pull request #5539
Opened 2022-02-06 16:08 UTC by s-tyshchenko

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [x] All tests are passing
- [x] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Issue: https://github.com/humhub/humhub/issues/5534

2022-02-06 16:54 UTC, luke- requested changes
@s-tyshchenko Unfortunately, this does not solve the problem. We also prefer "::class".

After a page reload the editor always works. The problem only occurs when navigating from another page to the statistics page (PJAX).

2022-02-06 17:06 UTC, ArchBlood commented on protected/humhub/modules/admin/views/setting/statistic.php
> +    <?= $form->field($model, 'trackingHtmlCode')->widget(CodeMirrorInputWidget::className()); ?>
This does not fix the issue causing the loading, not to mention is working backward with coding standards when using PHP 7.2+

Looking it over the issue seems to stem from the CodeMirrorInputWidget widget loading required scripts and CSS.

2022-02-07 13:12 UTC, luke- requested changes

2022-02-07 13:12 UTC, luke- commented on protected/humhub/modules/admin/views/setting/statistic.php
> +    <?= $form->field($model, 'trackingHtmlCode')->widget(CodeMirrorInputWidget::class); ?>
We should include the below javascript in the InputWidget class so that it doesn't have to be added separately for each view.

2022-02-07 13:12 UTC, luke- commented on protected/humhub/modules/admin/views/setting/statistic.php
> +<script>
We need to add 'Html::nonce()` here.Please see other Javascripts....

2022-02-07 13:12 UTC, luke- commented on protected/humhub/modules/admin/views/setting/statistic.php
> +    let initCodeMirrorTimeout = setTimeout(initCodeMirror, 200);
Hm, I would be very uncomfortable working with the timeouts.

Maybe this event do the trick?
https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.client.pjax.js#L44

2022-02-08 19:41 UTC, luke- requested changes
@s-tyshchenko I would like to avoid the timeout solution. Can you take a look at my comment?

2022-02-08 19:41 UTC, luke- commented on static/js/humhub/humhub.ui.codemirror.js
>          event.on('humhub:ready', function (evt) {
@s-tyshchenko Did you tried this event here?
https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.client.pjax.js#L44

2022-02-10 22:04 UTC, luke- commented
@s-tyshchenko Okay, let's leave it that way for now, even if the solution is not quite optimal.

Can you please check why the tests fail?

2022-02-11 11:05 UTC, luke- approved these changes

2022-02-11 11:05 UTC, merged