Autocomplete Input Widget
humhub/humhub pull request #5548
Opened 2022-02-10 16:55 UTC by s-tyshchenko

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Issue: https://github.com/humhub/humhub/issues/5538

I tried to use Select2 for this, but it didn't fit for such fields, the main reason was user inconvenience:
- First user need to click on the field, then click to focus on the input field in the dropdown and click on the suitable suggestion. This is how it looked like: 
<img width="911" alt="Снимок экрана 2022-02-10 в 11 44 50" src="https://user-images.githubusercontent.com/26685604/153455002-202136aa-613e-4302-ac74-e6c4fce017b7.png">

So I decided to build a new input widget with simple autocomplete functionality. It will load suggestions via AJAX, user can simply click on the suggestion and if will fill in the input field. If there aren't any suitable suggestions, the user can keep his inputted text (which was unable with Select2). This is how it looks like:

- for profile field:
<img width="944" alt="Снимок экрана 2022-02-10 в 18 12 54" src="https://user-images.githubusercontent.com/26685604/153454390-3131d639-b508-496e-9d26-55db052fd1a7.png">

- for people search filter:
<img width="1186" alt="Снимок экрана 2022-02-10 в 18 13 18" src="https://user-images.githubusercontent.com/26685604/153454500-b0979530-1b1c-4e74-9ce5-69b288987268.png">

2022-02-10 22:42 UTC, luke- commented
@s-tyshchenko Sorry if the PR was a little unclear. The field should appear at this point:
![image](https://user-images.githubusercontent.com/4736168/153508921-25ef76aa-7edb-437a-8469-cadf69d7ebe4.png)

You can add Profile Fields as Filter using this checkbox:
![image](https://user-images.githubusercontent.com/4736168/153509040-839218bf-ea5b-4242-9bfc-8cae4db45aa1.png)

2022-02-15 10:44 UTC, luke- commented
@s-tyshchenko Thanks. Yes please remove it on the full text search field:
![image](https://user-images.githubusercontent.com/4736168/154045981-f8c22ac7-fe3b-4fdc-a70b-87807c4f5b4e.png)

![image](https://user-images.githubusercontent.com/4736168/154046143-573a68f8-597e-4878-9958-398485a33d0d.png)

2022-02-17 12:37 UTC, luke- commented
@s-tyshchenko IWhen I select a value, the form is not submitted. Is this a prob or do I have a cache issue here?

2022-02-23 14:31 UTC, luke- requested changes
Please see my reviews

2022-02-23 14:31 UTC, luke- commented on protected/humhub/assets/AutocompleteInputAsset.php
> + * Color Picker js utility
Can you please fix the PHPDoc here.
Also add @since 1.11

2022-02-23 14:31 UTC, luke- commented on protected/humhub/assets/AutocompleteInputAsset.php
> + * @copyright Copyright (c) 2017 HumHub GmbH & Co. KG
22

2022-02-23 14:31 UTC, luke- commented on protected/humhub/modules/user/widgets/views/peopleFilterAutocompleteItem.php
> +    <?= $fullname ?>
Do we need `Html::encode` here?

2022-03-02 18:12 UTC, luke- commented on protected/humhub/compat/HForm.php
> +use humhub\modules\user\widgets\ProfileSettingsPicker;
@s-tyshchenko Why is this change required?

2022-03-14 10:46 UTC, luke- requested changes

2022-03-14 10:46 UTC, luke- commented on static/less/cards.less
> -                margin-bottom: 3px;
Doesn't this have any other effects? Can you please check this again?

2022-03-14 10:46 UTC, luke- commented on protected/humhub/modules/ui/form/widgets/BasePicker.php
> +            'data-multiple' => 'true',
Is it really required to modify BasePicker?

2022-03-14 10:46 UTC, luke- commented on protected/humhub/modules/user/controllers/AccountController.php
> +        return $this->asJson((new ProfileSettingsAutocomplete)->getAutocompleteSuggestions($field, $keyword));
Where is the method `getAutocompleteSuggestions`?

2022-03-17 16:31 UTC, s-tyshchenko commented on static/less/cards.less
> -                margin-bottom: 3px;
It fixed the placement of the search button:

This is with `margin-bottom: 3px;`:
<img width="53" alt="Снимок экрана 2022-03-17 в 18 29 10" src="https://user-images.githubusercontent.com/26685604/158848178-4710a789-52fb-4dcd-99c5-7abda4b9ca0e.png">

and without:
<img width="51" alt="Снимок экрана 2022-03-17 в 18 29 19" src="https://user-images.githubusercontent.com/26685604/158848171-9bab0f40-1b0a-4328-a451-921a6ca32406.png">

2022-03-17 21:59 UTC, luke- commented on static/less/cards.less
> -                margin-bottom: 3px;
@s-tyshchenko Thanks, can you please open a seperate PR for this? If there are side effects, we can then better trace it.

2022-03-18 12:32 UTC, luke- approved these changes

2022-03-18 12:33 UTC, merged