Possibility to create custom profile field types via modules
humhub/humhub pull request #5596
Opened 2022-03-16 20:35 UTC by KarlKeu00

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
- Enh #5560

2022-03-18 17:02 UTC, luke- requested changes
Thank you for your contribution!

2022-06-02 12:51 UTC, KarlKeu00 commented on protected/humhub/modules/user/models/fieldtype/BaseType.php
> +    const EVENT_INIT = "fieldTypesInit";
Done. I have also included an example.

2022-06-02 12:53 UTC, KarlKeu00 commented on protected/humhub/modules/user/models/fieldtype/BaseType.php
> +    public function __construct() {
Unfortunately, I have not yet understood the init method correctly, but I hope that it is now correct.

2022-06-03 05:54 UTC, luke- approved these changes

2022-06-03 05:59 UTC, luke- commented
Should be merged: Can you please check?
https://github.com/humhub/humhub/commit/bfb6bfe54934e8f19b49dffb13ff2c47c2339f0f

2022-06-03 05:59 UTC, closed without merging