Fix/membership request notification
humhub/humhub pull request #6243
Opened 2023-04-18 17:35 UTC by gevorgmansuryan

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
[Cannot delete notification for "join space" request](https://github.com/humhub/humhub/issues/6241)

2023-04-18 23:53 UTC, ArchBlood commented
Not sure the use of the word `actual` is the right one needed here, using `active` seems more useful here.

2023-04-19 12:46 UTC, luke- requested changes
Thanks, I think the approach fixes the bug. Can you scan for other Notifications or Situations which may have a similar problem?

2023-04-19 12:46 UTC, luke- commented on protected/humhub/modules/notification/components/BaseNotification.php
> +    public function isActual()
I also think we should improve the wording here.

What do you think about `$notification->isValid()`. This method should check if the notification should still exists, if not, the notification should be deleted.

2023-04-19 12:46 UTC, luke- commented on protected/humhub/modules/space/notifications/ApprovalRequest.php
> +     * @inerhitdoc +
`@inheritdoc`

2023-04-19 12:46 UTC, luke- commented on protected/humhub/modules/notification/components/BaseNotification.php
> +    public function isActual()
Please also add the as PHPDoc `@since 1.15`

2023-04-24 20:59 UTC, luke- approved these changes

2023-04-24 21:00 UTC, merged