Fix for displaying whether I follow a user. #6813
humhub/humhub pull request #6814
Opened 2024-01-23 15:37 UTC by sebastianSchmidt86

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

2024-01-23 15:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/humhub/humhub?pullRequest=6814) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/humhub/humhub?pullRequest=6814) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/humhub/humhub?pullRequest=6814) it.</sub>

2024-01-24 07:09 UTC, yurabakhtin requested changes

2024-01-24 07:09 UTC, yurabakhtin commented on protected/humhub/modules/user/behaviors/Followable.php
> +        return Yii::$app->runtimeCache->getOrSet(__METHOD__ . $this->owner->id, function () use ($userId) {
@sebastianSchmidt86 I see the record `Follow` is found by two values `$this->owner->getPrimaryKey()` and `$userId`, so I think it should be cached by these 2 values like this:

- `__METHOD__ . $this->owner->getPrimaryKey() . '-' . $userId`

2024-01-24 09:24 UTC, yurabakhtin approved these changes

2024-01-24 11:15 UTC, luke- approved these changes

2024-01-24 11:15 UTC, merged