Display notifications only of published contents
humhub/humhub pull request #6983
Opened 2024-05-01 12:16 UTC by yurabakhtin

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
https://github.com/humhub/humhub/issues/6869

2024-05-01 18:06 UTC, luke- approved these changes

2024-05-01 18:07 UTC, luke- requested changes
@yurabakhtin Can you please check the tests.

2024-05-02 06:44 UTC, yurabakhtin commented
> @yurabakhtin Can you please check the tests.

@luke- Fixed in the commit https://github.com/humhub/humhub/pull/6983/commits/c9cf6901ba53b33d3452b2c87b3830bdb396a65e.

2024-05-02 07:01 UTC, luke- approved these changes

2024-05-02 07:01 UTC, merged