Enh: Add search tests
humhub/humhub pull request #7033
Opened 2024-05-27 13:57 UTC by marc-farre

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: tests

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2024-05-27 15:32 UTC, luke- requested changes
@marc-farre Thanks for the test.

Are these only MySQL specific?

2024-05-28 07:42 UTC, marc-farre commented
> Are these only MySQL specific?

It shouldn't be, even if the main difference with SOLR is that we ignore terms with 1 or 2 chars.
But @yurabakhtin mentionned that we couldn't test SOLR because of ZendLucence not working for tests.

2024-05-28 12:06 UTC, luke- approved these changes

2024-05-28 14:46 UTC, luke- approved these changes

2024-05-28 14:47 UTC, merged