Fix: Allow using Space::canJoin($userId) in command line
humhub/humhub pull request #7066
Opened 2024-06-14 10:10 UTC by marc-farre

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2024-06-19 04:36 UTC, luke- requested changes
Do you need this urgently? Otherwise I would merge it for 1.17.

2024-06-19 04:36 UTC, luke- commented on protected/humhub/modules/space/models/Space.php
> +        if (!$userId) {
```suggestion
        $userId ??= Yii::$app->user->id;
```

2024-06-19 06:26 UTC, marc-farre commented
> Do you need this urgently? Otherwise I would merge it for 1.17.

@luke- Thanks for asking. 1.17 is fine.

2024-06-25 08:46 UTC, luke- approved these changes

2024-10-20 13:07 UTC, merged