space default stream sort
humhub/humhub pull request #7226
Opened 2024-09-23 15:54 UTC by gevorgmansuryan

https://github.com/humhub/humhub-internal/issues/377

2024-09-23 20:13 UTC, luke- commented
@gevorgmansuryan Thanks!

@yurabakhtin Can you please review?

2024-09-24 07:02 UTC, yurabakhtin requested changes

2024-09-24 08:12 UTC, luke- commented on protected/humhub/modules/admin/models/forms/SpaceSettingsForm.php
> +            Stream::SORT_UPDATED_AT => Yii::t('AdminModule.space', 'Last update'),
@yurabakhtin Good point! No better use the existing message category here.

@gevorgmansuryan Can you please adapt?

2024-09-25 06:05 UTC, yurabakhtin commented on protected/humhub/modules/admin/models/forms/SpaceSettingsForm.php
> +            Stream::SORT_UPDATED_AT => Yii::t('AdminModule.space', 'Last update'),
@gevorgmansuryan Could you please change the translation category from `AdminModule.space` to `ContentModule.base` for those 2 strings? It makes a work of translators easier :)

2024-09-25 23:12 UTC, gevorgmansuryan commented on protected/humhub/modules/admin/models/forms/SpaceSettingsForm.php
> +            Stream::SORT_UPDATED_AT => Yii::t('AdminModule.space', 'Last update'),
@yurabakhtin done. sorry just missed this point

2024-09-26 04:32 UTC, yurabakhtin approved these changes

2024-09-26 09:43 UTC, merged