.env Auto Install
humhub/humhub pull request #7239
Opened 2024-10-01 00:03 UTC by gevorgmansuryan

https://github.com/humhub/humhub-internal/issues/406

2024-10-02 11:14 UTC, luke- requested changes
@gevorgmansuryan Works good!

Would be great, if we also could automatically create the DB?
![image](https://github.com/user-attachments/assets/3abb9ec1-9791-44c7-b18a-2c04087d4d79)

2024-10-03 20:23 UTC, luke- commented
@gevorgmansuryan Works fine for me.

Please let me know when it's ready to merge. (e.g. Changelog)

2024-10-05 08:11 UTC, gevorgmansuryan commented
@luke- done

2024-10-05 20:30 UTC, luke- approved these changes

2024-10-05 20:31 UTC, merged