Always allow invitation by link
humhub/humhub pull request #7322
Opened 2024-11-28 09:06 UTC by yurabakhtin

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
https://github.com/humhub/humhub-internal/issues/460

2024-11-28 22:08 UTC, luke- requested changes
@yurabakhtin Thanks. Please see my remark.

2024-11-28 22:08 UTC, luke- commented on protected/humhub/modules/user/services/LinkRegistrationService.php
>      public function isEnabled(): bool
Can't we remove the method then?

2024-11-29 17:46 UTC, luke- requested changes
@yurabakhtin  Would it now still be possible to retrospectively deactivate link invitations, e.g. also via spaces?
e.g. the following scenario.

- Link registration is allowed
- In a space, this is used to an extreme extent. 
- Super Admin wants to deactivate it and ends link registration
---
Would registration with the space registration links still be possible?

2024-11-29 18:28 UTC, yurabakhtin commented
@luke- I have tested the Space case.

The feature "Invite by link" is visible on Space only when the general setting "Members can invite external users by link" is enabled:

![space-invite](https://github.com/user-attachments/assets/23ded327-2c37-4152-97c0-e78d0fc68881)

However if I disable the general setting I see the registration is still allowed if user has a link with a correct token.

Admin can reset token to new one by click "Create new link":
![reset-token](https://github.com/user-attachments/assets/0f840542-c241-47ad-80e1-04e49f702c0e)

We could reset ALL tokens(space and general) on each case when the setting "Members can invite external users by link" is updated from "enalbed" to "disabled". But it may be unclear for users because they will see the message:

![invalid-token](https://github.com/user-attachments/assets/f28c3d06-2530-4594-9851-cd36d9695c7c)

So it seems we should revert the method `isEnabled()` but use it only for Space case, right?

2024-11-30 13:34 UTC, marc-farre commented
@yurabakhtin @luke- I would say:
- no automatic token reset (because we might want to disable the feature for a day and enable it back later, the same links should still be working)
- When "Members can invite external users by link", the full feature is disabled (event previous links are not working anymore)
- Exception: System admins can still invite globally when the feature is disabled

Same behaviour with Email invitations.

But we have an issue with this: the invite link in the People page is the same as the one in the global admin page (for sys-admins).
So it is currently not possible to allow sys-admin links and not links from the People page:

![image](https://github.com/user-attachments/assets/118bebaf-89aa-4510-81f1-dab03e24a454)

![image](https://github.com/user-attachments/assets/02b6e1ce-f5c1-4b5a-87d6-46e89a7fb8ef)

So I think that ideally, the links should be different...

2024-11-30 22:54 UTC, luke- commented
@marc-farre Thanks, that sounds good to me. 

@yurabakhtin Can we implement it like that? Ideally +tests :-)

2024-12-02 11:35 UTC, yurabakhtin commented
@marc-farre To be sure what is required I would like to describe how it works now and what I have understood to implement:

Now:

1. We have 2 link token types: Global and Space. The Global is used from Administration and People pages. The Space token is generated per each space.
2. Registration is not blocked from the Global link now even when the setting "Members can invite external users by link" is disabled because Admins always have an access there.

New requirement:
1. Create a new link type: People.
2. Such link should have a different token than Global. I think to add a new param like `target=people` => `/user/registration/by-link?token=ygL9JR8erHfJlq&target=people`
3. Registration should be blocked from such link when "Members can invite external users by link" is disabled.
4. Registration from Global(Admin) link will never be blocked.

2024-12-02 12:06 UTC, marc-farre commented
@yurabakhtin Yes, it's exactly that, except that Now:
- Registration IS BLOCKED from the Global link now when the setting "Members can invite external users by link" is disabled despite that the Admins should always have an access there.

2024-12-02 14:16 UTC, yurabakhtin commented
> * Registration IS BLOCKED from the Global link now when the setting "Members can invite external users by link" is disabled despite that the Admins should always have an access there.

@marc-farre Sorry, I am confused in this point.
Do you want to block a registration when the setting "Members can invite external users by link" even that Admins have an access to generate such global links?
I thought it was a bug and we should make all global links enabled even when the setting is disabled, because Admins can generate such links and they may don't know the setting is disabled currently, so it will be strange if admin sends such global link to user and he will see error page instead of expected registration form.

Or when you wrote "Now" you mean how it works now without new changes from this PR.
When I wrote "Now" above I meant how it works with new changes from this PR.

2024-12-02 14:33 UTC, marc-farre commented
> Or when you wrote "Now" you mean how it works now without new changes from this PR.

I see. I meant currently (before PR). I miss understood "Now". 
Si everything is fine with your summary.

2024-12-03 08:36 UTC, yurabakhtin commented
@luke- @marc-farre Done, how it works now in this PR:

- New separate token has been inmplemented for the People page, it is stored as general setting `people.inviteToken`,
- Previous token is stored in the same setting `registration.inviteToken`, it is used for Administration part.
- I didn't add a new param like `target=people` as I wrote above, instead I have decided to detect a target by token value, so the links are different only by token value:
![diff_tokens](https://github.com/user-attachments/assets/d9fe7227-3d00-45b2-9093-f992ccad7d9d)

When the setting is **enabled**:
![link-enabled](https://github.com/user-attachments/assets/50d62c7f-cda8-4a57-b9dc-ab1a5a98c39f)

When **disabled**:
![link-disabled](https://github.com/user-attachments/assets/52b73b20-eb30-4ce6-ad68-d1d9d46eb9ae)

2024-12-03 10:05 UTC, marc-farre commented
@yurabakhtin That's really perfect, thanks!

2024-12-03 15:45 UTC, luke- approved these changes

2024-12-03 15:45 UTC, merged

2024-12-03 15:45 UTC, luke- commented
@yurabakhtin @marc-farre Thanks, looks fine for me too!